### ISSUE TITLE
LucasChess does not launch after upgrade to 2.19

### ISSUE THREAD

**Issue by vinyatu** [lukasmonk/lucaschessR2#183]
Does not launch after upgrade to 2.19 on Windows 10.
Traceback (most recent call last):
  File "LucasChessR\bin\LucasR.py", line 20, in <module>
  File "LucasChessR\bin\Code\Base\Init.py", line 4, in <module>
  File "LucasChessR\bin\Code\Procesador.py", line 59, in <module>
  File "LucasChessR\bin\Code\Leagues\ManagerLeague.py", line 29, in <module>
  File "LucasChessR\bin\Code\Leagues\WLeagues.py", line 7, in <module>
  File "LucasChessR\bin\Code\Leagues\WLeague.py", line 10, in <module>
ImportError: cannot import name 'EditPlayers' from 'Code.Leagues' (C:\Program Files (x86)\LucasChessR\bin\Code\Leagues\__init__.pyc)

**Comment by lukasmonk** [comment]
I don't understand what the problem is. Someone else has complained that it won't start either.
Could you send me a zip file with your Code folder inside the bin folder? So I can try to replicate the problem.

**Comment by vinyatu** [comment]
This is probably a Windows problem, since program starts normally on Linux

[Code.zip](https://github.com/user-attachments/files/18560585/Code.zip)

**Comment by lukasmonk** [comment]
I also think it is related to windows, there is a file that in theory should have been there for several versions and it is not in your folder, I don't know why it could have disappeared.
The correct Code folder is as follows:

[Code.zip](https://github.com/user-attachments/files/18562646/Code.zip)

**Comment by vinyatu** [comment]
Yes, copying this file (EditPlayers.pyc) essentially solves the problem. Interestingly, on examining MFT tables, vinyatu couldn't find a trace of this file - it's as if it never existed.
